import type { Metadata } from "next";
import "../shared/utils/globals.css";
import { ThemeProvider } from "../providers/theme.provider";
import { Navbar } from "../shared/components/navbar/index";
// import { Sidebar } from "../shared/components/sidebar/index";
import type { NavbarData } from "../shared/components/navbar/navbarTypes";
import type { NavItem } from "../shared/components/sidebar/sidebarTypes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getLayoutData(): Promise<{
  navbar: NavbarData;
  sidebar: NavItem[];
}> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        navbar: {
          logoUrl: "/logo.svg",
          documentationTitle: "My Documentation",
        },
        sidebar: [
          {
            id: "1",
            label: "Getting Started",
            children: [
              { id: "1-1", label: "Introduction", href: "/docs/intro" },
              { id: "1-2", label: "Installation", href: "/docs/install" },
            ],
          },
          {
            id: "2",
            label: "Guides",
            children: [
              { id: "2-1", label: "Routing", href: "/docs/routing" },
              { id: "2-2", label: "Layouts", href: "/docs/layouts" },
            ],
          },
          {
            id: "3",
            label: "API Reference",
            href: "/docs/api",
          },
        ],
      });
    }, 1000);
  });
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getLayoutData();

  return (
    <html lang="fa">
      <body>
        <ThemeProvider>
          <div className="flex flex-col">
            <Navbar data={data.navbar} sidebarItems={data.sidebar} />
            <div className="flex mt-16 bg-rose-400">
              {/* <Sidebar items={data.sidebar} /> */}
              <main className="flex-1">{children}</main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
